DepartamentosCoreCRUD/Models/Departamento.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DepartamentosCoreCRUD.Models
{
    public class Departamento
    {
        public int Numero { get; set; }
        public String Nombre { get; set; }
        public String Localidad { get; set; }
    }
}

DepartamentosCoreCRUD/Models/ErrorViewModel.cs
using System;

namespace DepartamentosCoreCRUD.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DepartamentosCoreCRUD/Controllers/DepartamentosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DepartamentosCoreCRUD.Data;
using DepartamentosCoreCRUD.Models;

namespace DepartamentosCoreCRUD.Controllers
{
    public class DepartamentosController : Controller
    {
        DepartamentosContext context;
        public DepartamentosController(DepartamentosContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            List<Departamento> listadepartamentos = this.context.GetDepartamentos();
            return View(listadepartamentos);
        }
        public IActionResult Details(int iddepartamento)
        {
            Departamento departamento = this.context.FindDepartamento(iddepartamento);
            return View(departamento);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(int iddepartamento, String nombre, String localidad)
        {
            this.context.InsertarDepartamento(iddepartamento, nombre, localidad);
            //para que nos envie a otra vista
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int iddepartamento)
        {
            Departamento departamento = this.context.FindDepartamento(iddepartamento);
            return View(departamento);
        }
        [HttpPost]
        public IActionResult Edit(int iddepartamento, String nombre, String localidad)
        {
            this.context.UpdateDepartamento(iddepartamento, nombre, localidad);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int iddepartamento)
        {
            this.context.DeleteDepartamento(iddepartamento);
            return RedirectToAction("Index");
        }
    }
}

DepartamentosCoreCRUD/Controllers/HomeController.cs
using DepartamentosCoreCRUD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DepartamentosCoreCRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DepartamentosCoreCRUD/Views/Departamentos/Create.cshtml
<h1>Nuevo departamento</h1>

<form method="post">
    <label>Número</label>
    <input type="number" name="iddepartamento"
           class="form-control" /><br />
    <label>Nombre</label>
    <input type="text" name="nombre"
           class="form-control" /><br />
    <label>Localidad</label>
    <input type="text" name="localidad"
           class="form-control" /><br />
    <button class="btn btn-success">
        Insertar departamento
    </button>
</form>

DepartamentosCoreCRUD/Views/Departamentos/Details.cshtml
@model Departamento

    <a asp-controller="Departamentos"
       asp-action="Index">
        Volver al listado
    </a>
    <hr />

    <ul class="list-group">
        <li class="list-group-item">
            Nombre: @Model.Nombre
        </li>
        <li class="list-group-item">
            Número: @Model.Numero
        </li>
        <li class="list-group-item">
            Localidad: @Model.Localidad
        </li>
    </ul>

DepartamentosCoreCRUD/Views/Departamentos/Edit.cshtml
@model Departamento

<h1>Editar departamento</h1>
<form method="post">
    <label>Número</label>
    <input type="number" name="iddepartamento"
           value="@Model.Numero" disabled
           class="form-control" /><br />
    <label>Nombre</label>
    <input type="text" name="nombre" 
           value="@Model.Nombre" 
           class="form-control" /><br />
    <label>Localidad</label>
    <input type="text" name="localidad" 
           value="@Model.Localidad" 
           class="form-control" /><br />
    <button class="btn btn-success">
        Modificar
    </button>
</form>

DepartamentosCoreCRUD/Views/Departamentos/Index.cshtml
@model List<Departamento>



<table class="table table-dark">
    <thead>
        <tr>
            <th>Número</th>
            <th>Nombre</th>
            <th>Localidad</th>
        </tr>
    </thead>
    <tbody>
        @foreach(Departamento dept in Model)
        {
        <tr>
            <td>@dept.Numero</td>
            <td>@dept.Nombre</td>
            <td>@dept.Localidad</td>
            <td>
                <a class="btn btn-info"
                   asp-controller="Departamentos"
                   asp-action="Details"
                   asp-route-iddepartamento="@dept.Numero">
                    Detalles
                </a>
                <a class="btn btn-info"
                   asp-controller="Departamentos"
                   asp-action="Edit"
                   asp-route-iddepartamento="@dept.Numero">
                    Editar
                </a>
                <a class="btn btn-danger"
                   asp-controller="Departamentos"
                   asp-action="Delete"
                   asp-route-iddepartamento="@dept.Numero">
                    Eliminar
                </a>
            </td>
        </tr>
        }
    </tbody>
</table>

DepartamentosCoreCRUD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DepartamentosCoreCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DepartamentosCoreCRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DepartamentosCoreCRUD</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-controller="Departamentos"
                               asp-action="Index">
                                Departamentos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-controller="Departamentos" 
                               asp-action="Create">
                            Nuevo departamento
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DepartamentosCoreCRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>